"""Chat backend using ClaudeSDKClient."""

from __future__ import annotations

import asyncio
import json
import re
import time
import urllib.request
from collections.abc import AsyncIterator

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from claude_agent_sdk import AssistantMessage, ClaudeAgentOptions, TextBlock, query

from mkdocs_claude_chat._internal.logger import get_logger

_logger = get_logger(__name__)

# ── Server config (set by plugin at startup) ──────────────────────────────────
_llmstxt_url: str = ""


def configure(llmstxt_url: str) -> None:
    """Set the docs index URL. Called by the MkDocs plugin after each build."""
    global _llmstxt_url
    _llmstxt_url = llmstxt_url
    _logger.info("claude-chat: docs index → %s", llmstxt_url)


# Limit concurrent Claude subprocesses to avoid resource exhaustion.
# Each active user gets their own claude CLI process; this caps the total.
_MAX_CONCURRENT = 10
_semaphore: asyncio.Semaphore | None = None  # created lazily inside the event loop


def _get_semaphore() -> asyncio.Semaphore:
    global _semaphore
    if _semaphore is None:
        _semaphore = asyncio.Semaphore(_MAX_CONCURRENT)
    return _semaphore


# ── Conversation history ──────────────────────────────────────────────────────
# Keyed by session_id (generated by the browser widget per page load).
# Each entry is a list of {"role": "user"|"assistant", "content": str}.
# Sessions expire after 2 hours of inactivity.
_SESSION_TTL = 7200  # seconds
_sessions: dict[str, tuple[float, list[dict[str, str]]]] = {}


def _get_history(session_id: str) -> list[dict[str, str]]:
    entry = _sessions.get(session_id)
    if entry and time.monotonic() - entry[0] < _SESSION_TTL:
        return entry[1]
    return []


def _append_history(session_id: str, role: str, content: str) -> None:
    history = _get_history(session_id)
    history.append({"role": role, "content": content})
    _sessions[session_id] = (time.monotonic(), history)


# ── Docs cache ────────────────────────────────────────────────────────────────
# Keyed by llmstxt_url. Refreshed at most once every 15 seconds so hot-reloads
# are picked up quickly without hammering the dev server on every message.
_CACHE_TTL = 15  # seconds
_docs_cache: dict[str, tuple[float, str]] = {}  # url -> (timestamp, content)


def _fetch_sync(url: str, timeout: int = 5) -> str:
    """Blocking HTTP fetch. Run via asyncio.to_thread to avoid blocking the event loop."""
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:  # noqa: S310
            return resp.read().decode("utf-8", errors="replace")
    except Exception as exc:  # noqa: BLE001
        _logger.debug("fetch failed %s: %s", url, exc)
        return ""


def _base_url(llmstxt_url: str) -> str:
    """Return the base URL (everything before the filename)."""
    return llmstxt_url.rsplit("/", 1)[0] + "/"


async def _load_docs(llmstxt_url: str) -> str:
    """Fetch and return documentation content for the given llms.txt URL.

    Strategy:
    1. Try ``<base>/llms-full.txt`` — a single file with all docs concatenated.
    2. Fall back: fetch ``llms.txt``, parse every markdown link, fetch each page.

    Fetches run in a thread pool so the asyncio event loop stays unblocked,
    allowing concurrent users to be served simultaneously.

    Results are cached for :data:`_CACHE_TTL` seconds.
    """
    now = time.monotonic()
    cached = _docs_cache.get(llmstxt_url)
    if cached and now - cached[0] < _CACHE_TTL:
        return cached[1]

    base = _base_url(llmstxt_url)

    # Try llms-full.txt first (all docs in one file — one fetch for all users)
    content = await asyncio.to_thread(_fetch_sync, base + "llms-full.txt")

    if not content:
        # Fall back: fetch index then each linked page concurrently
        index = await asyncio.to_thread(_fetch_sync, llmstxt_url)
        if index:
            page_urls = []
            for match in re.finditer(r"\[([^\]]+)\]\(([^)]+)\)", index):
                page_url = match.group(2)
                if not page_url.startswith("http"):
                    page_url = base + page_url.lstrip("/")
                page_urls.append(page_url)

            pages = await asyncio.gather(*[
                asyncio.to_thread(_fetch_sync, url) for url in page_urls
            ])
            parts = [index] + [
                f"\n\n---\n<!-- source: {url} -->\n\n{page}"
                for url, page in zip(page_urls, pages) if page
            ]
            content = "\n".join(parts)

    _docs_cache[llmstxt_url] = (now, content)
    _logger.debug("loaded docs (%d chars) from %s", len(content), llmstxt_url)
    return content


# ── System prompts ────────────────────────────────────────────────────────────

_SYSTEM_PROMPT_WITH_DOCS = """\
You are a documentation assistant. The full documentation content is provided below — \
use it as your primary knowledge source.

## Documentation

{docs_content}

---

## Instructions

- Answer based on the documentation above.
- Quote or reference specific sections when helpful.
- If the question is not covered in the docs, say so clearly, \
then you may supplement with general knowledge — label it as "(outside the docs)".
- Keep answers concise and accurate.\
"""

_SYSTEM_PROMPT_NO_DOCS = """\
You are a documentation assistant. No documentation content was found.

Try to help the user as best you can using your general knowledge, \
but make it clear you are not drawing from site-specific documentation.\
"""


class ChatRequest(BaseModel):
    """Request body for the POST /chat endpoint.

    Attributes:
        question: The user's question about the documentation.
        llmstxt_url: URL of the site's llms.txt index. The server fetches it
            directly so Claude does not need localhost access.
        system_prompt: Optional override for the system prompt.
        session_id: Browser-generated ID to maintain conversation history
            across multiple messages in the same chat session.
    """

    question: str
    llmstxt_url: str = ""
    system_prompt: str = ""
    session_id: str = ""


app = FastAPI(title="mkdocs-claude-chat server", docs_url=None, redoc_url=None)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


async def _build_system_prompt(llmstxt_url: str) -> str:
    """Build the system prompt, pre-loading doc content from *llmstxt_url*.

    The server fetches the documentation itself (it has localhost access)
    and injects the content directly so Claude never needs network access.
    All fetches are non-blocking so concurrent users are not serialised.

    Args:
        llmstxt_url: URL of the site's llms.txt (or llms-full.txt base).

    Returns:
        Formatted system prompt string with docs embedded.
    """
    if not llmstxt_url:
        return _SYSTEM_PROMPT_NO_DOCS

    docs = await _load_docs(llmstxt_url)
    if not docs:
        _logger.warning("could not load docs from %s — Claude will answer without context", llmstxt_url)
        return _SYSTEM_PROMPT_NO_DOCS

    return _SYSTEM_PROMPT_WITH_DOCS.format(docs_content=docs)


async def _stream_claude(question: str, llmstxt_url: str, system_prompt: str = "", session_id: str = "") -> AsyncIterator[str]:
    """Run a Claude session and yield SSE-formatted text chunks.

    Args:
        question: The user's question.
        llmstxt_url: URL of the docs index — fetched server-side and injected
            into the system prompt so Claude does not need localhost access.
        system_prompt: Optional caller-supplied prompt override.

    Yields:
        SSE strings: ``data: {"text": "..."}\\n\\n`` per chunk,
        then ``data: [DONE]\\n\\n``.
    """
    resolved_prompt = system_prompt.strip() or await _build_system_prompt(llmstxt_url)

    # Prepend conversation history to the question so Claude remembers prior turns.
    history = _get_history(session_id) if session_id else []
    if history:
        history_text = "\n".join(
            f"{'User' if h['role'] == 'user' else 'Assistant'}: {h['content']}"
            for h in history
        )
        full_question = f"## Previous conversation\n\n{history_text}\n\n## Current question\n\n{question}"
    else:
        full_question = question

    if session_id:
        _append_history(session_id, "user", question)

    options = ClaudeAgentOptions(
        system_prompt=resolved_prompt,
        permission_mode="bypassPermissions",
        allowed_tools=["Bash", "WebFetch", "WebSearch"],
    )

    assistant_reply: list[str] = []
    sem = _get_semaphore()
    if sem.locked() and sem._value == 0:  # noqa: SLF001
        yield f"data: {json.dumps({'error': 'Server busy — too many concurrent users. Please try again shortly.'})}\n\n"
        yield "data: [DONE]\n\n"
        return

    async with sem:
        try:
            async for message in query(prompt=full_question, options=options):
                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock) and block.text:
                            assistant_reply.append(block.text)
                            yield f"data: {json.dumps({'text': block.text})}\n\n"
        except Exception as exc:  # noqa: BLE001
            _logger.error("Claude session error: %s", exc)
            yield f"data: {json.dumps({'error': str(exc)})}\n\n"

    if session_id and assistant_reply:
        _append_history(session_id, "assistant", "".join(assistant_reply))

    yield "data: [DONE]\n\n"


@app.get("/health")
async def health() -> dict[str, str]:
    """Liveness check endpoint."""
    return {"status": "ok"}


@app.post("/chat")
async def chat(request: ChatRequest) -> StreamingResponse:
    """Stream a Claude answer to the user's question.

    Args:
        request: The chat request.

    Returns:
        A streaming SSE response ending with ``data: [DONE]``.
    """
    # Use the server-configured URL; fall back to whatever the browser sent.
    effective_url = _llmstxt_url or request.llmstxt_url
    _logger.debug("chat request: question=%r, session=%r, llmstxt_url=%r", request.question, request.session_id, effective_url)
    return StreamingResponse(
        _stream_claude(request.question, effective_url, request.system_prompt, request.session_id),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


def run(port: int = 8001) -> None:
    """Start the chat server on the given port.

    Args:
        port: TCP port to listen on. Defaults to ``8001``.
    """
    _logger.info("starting chat server on port %d", port)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="warning")
